cd \Kiosk\Precos\
@echo off
setlocal enabledelayedexpansion
echo .
echo .
echo INICIO TRANSFERENCIA ARQUIVO DE PRECOS DO GATEWAY

Start /b /wait PRECO_CONSULTA.bat

echo CASO GATEWAY ESTEJA FORA TIRAR O ECHO DA LINHA DE BAIXO

echo INICIO TRANSFERENCIA ARQUIVO DE PRECOS DO PDV

echo Start /b /wait PRECO_CONSULTA_PDV.bat

echo TERMINO TRANSFERENCIA ARQUIVO DE PRECOS DO GATEWAY

echo INICIO CONVERSAO ARQUIVO DE PRECOS 

Start /b /wait MAIN.EXE

echo TERMINO CONVERSAO ARQUIVO DE PRECOS 

EXIT